services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: cubot-api-test
    environment:
      SECRET_KEY: test_secretkeyb3c4d5e6f7g8lnastwfpb_3*q8r9s0t1u2
      DJANGO_SETTINGS_MODULE: cubot.settings
      DB_HOST: db
      DB_USER: postgres
      DB_NAME: cubot_db_test
      DB_PORT: 5432
      DB_PASSWORD: postgres
    depends_on:
      - db
    command: ["pytest"]

  db:
    image: postgres:16
    container_name: cubot-db-test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cubot_db_test

