FROM python:3.12

RUN apt-get update && apt-get install -y --no-install-recommends \
    binutils \
    build-essential \
    gettext \
    libproj-dev \
    python3-dev \
    wget \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean

ENV DOCKERIZE_VERSION v0.6.1
RUN wget --secure-protocol=TLSv1_2 --max-redirect=5 https://github.com/jwilder/dockerize/releases/download/"$DOCKERIZE_VERSION"/dockerize-linux-amd64-"$DOCKERIZE_VERSION".tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-"$DOCKERIZE_VERSION".tar.gz \
    && rm dockerize-linux-amd64-"$DOCKERIZE_VERSION".tar.gz

RUN curl -LsSf https://astral.sh/uv/install.sh | sh \
    && mv /root/.local/bin/uv /usr/local/bin/

WORKDIR /app

COPY pyproject.toml uv.lock ./
RUN uv pip install --system --group main --group dev

COPY . .

COPY entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

EXPOSE 3031

ENTRYPOINT [ "/app/entrypoint.sh" ]
