# Generated by Django 5.2.4 on 2025-07-15 02:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="conversation",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="conversationmessage",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="conversationmessage",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
