# Generated by Django 5.2.4 on 2025-07-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_alter_conversation_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="topic",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
